server:
  port: 8089

spring:
  application:
    name: Payment-service
  datasource:
    url: jdbc:postgresql://localhost:5434/payment_db
    username: payment_user
    password: payment_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment_group
      auto-offset-reset: earliest
    topic:
      new-orders:
        partitions: 3